# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        """

        Código obtenido a partir del fichero xml generado por QtDesigner para la interfaz grafica de aviso

        :param windowaviso: Interfaz gráfica
        :type windowaviso: Object

        """
        windowaviso.setObjectName("windowaviso")
        windowaviso.setWindowModality(QtCore.Qt.NonModal)
        windowaviso.resize(360, 200)
        windowaviso.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(100, 130, 161, 23))
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.lblImageAviso = QtWidgets.QLabel(windowaviso)
        self.lblImageAviso.setGeometry(QtCore.QRect(150, 20, 61, 51))
        self.lblImageAviso.setText("")
        self.lblImageAviso.setPixmap(QtGui.QPixmap("img/Warning.png"))
        self.lblImageAviso.setScaledContents(True)
        self.lblImageAviso.setObjectName("lblImageAviso")
        self.lblAviso = QtWidgets.QLabel(windowaviso)
        self.lblAviso.setGeometry(QtCore.QRect(120, 70, 158, 51))
        self.lblAviso.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.lblAviso.setObjectName("lblAviso")

        self.retranslateUi(windowaviso)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Aviso"))
        self.lblAviso.setText(_translate("windowaviso", "Desea salir?"))
